REM INSERTING into EXPORT_TABLE
SET DEFINE OFF;
Insert into EXPORT_TABLE (DB_CONNECT_CODE,SYS_CREATION_DATE,SYS_UPDATE_DATE,OPERATOR_ID,APPLICATION_ID,DL_SERVICE_CODE,DL_UPDATE_STAMP,DB_INSTANCE,DB_INSTANCE_NODE,DB_USER_TYPE,DB_USER_XMKT_IND,DB_USER_MKT,USERNAME,PASSWORD) values ('O2OTREF4  ',to_date('05-JAN-99','DD-MON-RR'),null,9988,null,null,null,'O2OTREF4  ','inceee020 ','R','Y','O2O',null,null);
