REM INSERTING into EXPORT_TABLE
SET DEFINE OFF;
Insert into EXPORT_TABLE (DB_INSTANCE,SYS_CREATION_DATE,SYS_UPDATE_DATE,OPERATOR_ID,APPLICATION_ID,DL_SERVICE_CODE,DL_UPDATE_STAMP,DB_INSTANCE_NODE,DB_INSTANCE_DESC) values ('O2OEXC    ',to_date('31-DEC-13','DD-MON-RR'),to_date('31-DEC-13','DD-MON-RR'),null,null,'Harsh',null,'inceee020 ','PMX EXC DB                    ');
