REM INSERTING into DB_INSTANCE_NODE
SET DEFINE OFF;
Insert into DB_INSTANCE_NODE (DB_INSTANCE_NODE,SYS_CREATION_DATE,SYS_UPDATE_DATE,OPERATOR_ID,APPLICATION_ID,DL_SERVICE_CODE,DL_UPDATE_STAMP,DB_INST_NODE_DESC) values ('O2OEXC    ',to_date('31-DEC-13','DD-MON-RR'),to_date('31-DEC-13','DD-MON-RR'),null,null,'Harsh',null,'PMX EXC DB                    ');
